### ISSUE TITLE
Session token not found

### ISSUE THREAD

**Issue by reyhansofian** [infusionsoft/api-oauth-php-lumen#1]
Hi! I'm quite new with Infusionsoft API. I'm using Laravel and I'm following [this tutorial](https://developer.infusionsoft.com/tutorials/using-the-infusionsoft-php-sdk-with-a-microframework/#exchange-the-code-for-an-access-token). I just started with **Exchange the Code for an Access Token**. And I just realized that there's no session named `token` by debugging using `$request->session('token')` after redirect back to my site and all I got is Laravel session. My code looks like this
```
public function key(Request $request)
    {
        // Setup a new Infusionsoft SDK object
        $infusionsoft = new Infusionsoft(array(
            'clientId'     => getenv('INFUSIONSOFT_CLIENT_ID'),
            'clientSecret' => getenv('INFUSIONSOFT_CLIENT_SECRET'),
            'redirectUri'  => getenv('INFUSIONSOFT_REDIRECT_URL'),
        ));

        // If the serialized token is already available in the session storage,
        // we tell the SDK to use that token for subsequent requests, rather
        // than try and retrieve another one.
        if ($request->has('token')) {
            $infusionsoft->setToken(unserialize($request->session('token')));
        }

        // If we are returning from Infusionsoft we need to exchange the code
        // for an access token.
        if ($request->has('token') and !$infusionsoft->getToken()) {
            $infusionsoft->requestAccessToken($request->get('code'));
        }

        dd($infusionsoft);
    }
```

**Comment by kressaty** [comment]
Your code differs from the tutorial's - you can't use `$request->has('token')` because that doesn't check the session afaik (it only checks the get/post data), but you'd need to reference the Laravel documentation to investigate that further. I'd imagine that's the issue; properly checking and setting the token should solve it. No issue on the repo.
